# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df6b1bd87a6339cebe4e1a08d73d19628626a7fde9a5cbe083a3e6221a177c75b1585b3455b3ad9e85c28561d6da9fdfd5f5b76cdeb726a37f44aa8285654d70

test:
  secret_key_base: 26627a5e209576c504f7872c063eff11739c667b17099a8c0769bf4b92c65b68e2fb1e8005d6c8d70d5ef01006546dc97703eb9eefb7251a8ebfd0de137b1889

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
